# Site settings
title: 2OutFull
email: ggamini7@gmail.com
description: Give us A+
baseurl: ""
url: "http://2outfull.Github.io"

author:
  name     : 'Hamin Lee'
  email    : ggamini7@gmail.com
  url      : http://2outfull.Github.io
  facebook : 
  twitter  : 

github: https://github.com/2OutFull
disqus_shortname: "hamin"
google_analytics: UA-52446115-1

paginate: 10
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
